project:
  type: website
  output-dir: ../docs

website:
  title: "Quarto Website Demo"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Quarto project"
        contents:
          - index.qmd
          - quarto-proj.qmd
      - section: "Quarto website"
        contents:
          - quarto-web.qmd
  listing:
    contents: posts

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



